# Generated by Django 5.1.4 on 2024-12-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='nameservice',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
