# Generated by Django 5.1.4 on 2024-12-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_evaluationcriteria_evaluation_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluationCriteria',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='period',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='criteria',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluation_type',
            field=models.CharField(choices=[('Annual', 'Annual'), ('Semi-Annual', 'Semi-Annual')], default='Annual', max_length=20),
        ),
    ]
