# Generated by Django 5.1.4 on 2024-12-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_conge'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='jours_restants',
            field=models.IntegerField(default=0),
        ),
    ]
